#!/bin/bash

# Run from the root of joda-time

echo "Files: $(find src/main/java -name '*.java' | wc -l)"
echo "Array uses: $(grep '\[.*\]' -r src/main/java | wc -l)"
echo
echo "Annotations:"
echo "IndexFor: $(grep '@IndexFor' -r src/main/java | wc -l)"
echo "IndexOrHigh: $(grep '@IndexOrHigh' -r src/main/java | wc -l)"
echo "IndexOrLow: $(grep '@IndexOrLow' -r src/main/java | wc -l)"
echo "Positive: $(grep '@Positive' -r src/main/java | wc -l)"
echo "NonNegative: $(grep '@NonNegative' -r src/main/java | wc -l)"
echo "GTENegativeOne: $(grep '@GTENegativeOne' -r src/main/java | wc -l)"
echo "LTLengthOf: $(grep '@LTLengthOf' -r src/main/java | wc -l)"
echo "LTEqLengthOf: $(grep '@LTEqLengthOf' -r src/main/java | wc -l)"
echo "LTOMLengthOf: $(grep '@LTOMLengthOf' -r src/main/java | wc -l)"
echo "MinLen: $(grep '@MinLen' -r src/main/java | wc -l)"
echo "SameLen: $(grep '@SameLen' -r src/main/java | wc -l)"
echo
echo
echo "Suppressions:"
echo "index:array.access.unsafe.high: $(grep 'index:array.access.unsafe.high' -r src/main/java | wc -l)"
echo "index:array.access.unsafe.low: $(grep 'index:array.access.unsafe.low' -r src/main/java | wc -l)"
echo "index:array.length.negative: $(grep 'index:array.length.negative' -r src/main/java | wc -l)"
echo "index:argument: $(grep 'index:argument' -r src/main/java | wc -l)"
echo "index:return: $(grep 'index:return' -r src/main/java | wc -l)"
echo "index:assignment: $(grep 'index:assignment' -r src/main/java | wc -l)"
echo "index:override: $(grep 'index:override' -r src/main/java | wc -l)"
echo "index: $(grep '@SuppressWarnings("index")' -r src/main/java | wc -l)"
